title: LIWFAY.COM
author: LIWFAY
# email: liwfay@outlook.com
# description: >-
#   年度精选

social:
  github: LIWFAY
  weibo: LIWFAY

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  images:
    output: true
