title: LIWFAY.COM
author: LIWFAY
email: liwfay@outlook.com
description: >-
  Copyright 2024 LIWFAY

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  images:
    output: true
