title: LIWFAY.COM
author: LIWFAY
email: liwfay@outlook.com
description: >-
  欢迎关注本站, 点击下方查看更多关于作者的社交信息

social:
  twitter: joaomlneto
  facebook: joaomlneto
  instagram: joaomlneto
  github: joaomlneto

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  images:
    output: true
